name: Archived repository

on:
  workflow_dispatch:

jobs:
  archived:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Development moved to wizzomafizzo/mrext"
